# To create the YAML structure you provided, follow these steps:

# Define the Tables:

# Start by defining the tables in your YAML document. Each table should have a unique name as the key.
# Set the Count:

# For each table, specify the count attribute to determine how many rows of data you want to generate for that table.
# Define Columns:

# Under each table, list the columns with their respective attributes.
# For each column, specify its name, type, and other relevant properties such as minimum and maximum values, length, padding, and faker functions.
# Types of Columns:

# Different types of columns can include int, string, float, datetime, and dependent.
# For dependent columns, specify the table and column it depends on.
# Define Faker Functions:

# For string columns, you can use faker functions to generate random data like names, words, UUIDs, etc.
# Specify the faker function using the fake attribute and provide any necessary parameters.
# Define Concatenated Columns:

# If you have columns where the value is generated by concatenating other fields, use the generate: concatenate attribute and list the fields to concatenate under the fields attribute.
# Define Distribution for Boolean Columns:

# For boolean columns, you can specify a distribution of values using the distribution attribute.
# Provide the distribution percentages for each value.
# Save the YAML Document:

# Once you have defined all the tables and columns, save the YAML document with a .yaml extension.
# Here's a basic template for the YAML document based on your provided structure:


# account_table:
#   count: 10
#   columns:
#     customer_no:
#       type: int
#       min: 1
#       max: 1000000
#       length: [7, 10]
#       pad_with_zeros: true
#     # Define other columns...

# product_table:
#   count: 50
#   columns:
#     item_no:
#       type: int
#       min: 1
#       max: 99999
#       length: 5
#     # Define other columns...

# sales_table:
#   count: 500
#   columns:
#     site_no:
#       type: dependent
#       depends_on:
#         table: product_table
#         column: site_no
#     # Define other columns...

dimension_table_1:
  count: 50
  columns:
    id:
      type: int
      min: 1
      max: 50
    name:
      type: string
      fake: name
    gender:
      type: string
      fake: random_element
      values: [Male, Female]
      distribution:
        - Male: 80%
        - Female: 20%
    age:
      type: int
      min: 18
      max: 80
    email:
      type: string
      fake: email

dimension_table_2:
  count: 20
  columns:
    id:
      type: int
      min: 1
      max: 20
    company_name:
      type: string
      fake: company
    industry:
      type: string
      fake: random_element
      values: [Technology, Healthcare, Finance, Retail, Education]
    revenue:
      type: decimal
      min: 100000.00
      max: 10000000.00
      precision: 2
    employees:
      type: int
      min: 50
      max: 1000

dimension_table_3:
  count: 30
  columns:
    id:
      type: int
      min: 1
      max: 30
    product_name:
      type: string
      fake: product_name
    category:
      type: string
      fake: random_element
      values: [electronics, clothing, furniture, books, toys]
    price:
      type: decimal
      min: 10.00
      max: 1000.00
      precision: 2
    stock_quantity:
      type: int
      min: 10
      max: 1000

dimension_table_4:
  count: 40
  columns:
    id:
      type: int
      min: 1
      max: 40
    city:
      type: string
      fake: city
    country:
      type: string
      fake: country
    population:
      type: int
      min: 10000
      max: 10000000
fact_table:
  count: 100
  columns:
    id:
      type: int
      min: 1
      max: 100
    id1:
      type: dependent
      depends_on:
        table: dimension_table_1
        column: id
    id2:
      type: dependent
      depends_on:
        table: dimension_table_2
        column: id
    id3:
      type: dependent
      depends_on:
        table: dimension_table_3
        column: id
    id4:
      type: dependent
      depends_on:
        table: dimension_table_4
        column: id
    date:
      type: datetime
      start: "2022-01-01"
      end: "2022-12-31"
    amount:
      type: decimal
      min: 100.00
      max: 10000.00
      precision: 2
    category:
      type: string
      fake: random_element
      values: [electronics, clothing, furniture, books, toys]
    customer_id:
      type: int
      min: 1
      max: 100
    product_id:
      type: int
      min: 1
      max: 100